
//======================================================= 
//  This code is generated by Terasic System Builder 
//======================================================= 
`timescale 1ps/1ps
module tb_lab1_part2;
//stores count in a register
 reg[3:0] count;
 //Assigns hardware to wires
 //////////// SEG7 ////////// 
 wire         [7:0]  HEX0;
 wire         [7:0]  HEX1; 
 wire         [7:0]  HEX2; 
 wire         [7:0]  HEX3; 
 wire         [7:0]  HEX4; 
 wire         [7:0]  HEX5; 
 //////////// SW ////////// 
 wire         [9:0]  SW;
//Assigns count to the switches
 assign SW[3:0] = count;

// Instantiates hardware 
 lab1_part2 Lab1_DUT (.HEX0(HEX0), .HEX1(HEX1), .HEX2(HEX2),  
   .HEX3(HEX3), .HEX4(HEX4), .HEX5(HEX5), 
   .KEY(KEY), .LEDR(LEDR), .SW(SW)); 
	
 initial begin   
    count = 4'b0000;
	 //Declares count as zero
    repeat (16) begin 
	 //Loops 16 times for each output
  #100
  //Prints all outputs after a time delay
  $display("in = %b, out = %b", count, HEX1[6]);
  $display("in = %b, out = %b", count, HEX1[5]);
  $display("in = %b, out = %b", count, HEX1[4]);
  $display("in = %b, out = %b", count, HEX1[3]);
  $display("in = %b, out = %b", count, HEX1[2]);
  $display("in = %b, out = %b", count, HEX1[1]);
  $display("in = %b, out = %b", count, HEX1[0]);

  $display("in = %b, out = %b", count, HEX0[6]);
  $display("in = %b, out = %b", count, HEX0[5]);
  $display("in = %b, out = %b", count, HEX0[4]);
  $display("in = %b, out = %b", count, HEX0[3]);
  $display("in = %b, out = %b", count, HEX0[2]);
  $display("in = %b, out = %b", count, HEX0[1]);
  $display("in = %b, out = %b", count, HEX0[0]);
//Increments count
  count = count + 4'b0001; 
    end 
  end 
endmodule 



