
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module add3_error(
	//////////// INPUT //////////
	input [2:0] in1,
	input [2:0] in2,
	input       ci,

	//////////// OUTPUT //////////
	output reg [3:0] sum
	//output       co
);

wire temp_0;
wire temp_1;
wire [3:0] temp_sum;


//=======================================================
//  Structural coding
//=======================================================

fa FullAdder0(.a(in1[0]), .b(in2[0]), .ci(ci), .s(temp_sum[0]), .co(temp_0));
fa FullAdder1(.a(in1[1]), .b(in2[1]), .ci(temp_0), .s(temp_sum[1]), .co(temp_1));
fa FullAdder2(.a(in1[2]), .b(in2[2]), .ci(temp_1), .s(temp_sum[2]), .co(temp_sum[3]));


always @* begin
	sum = temp_sum;
	if ((in1 == 3'b111 && in2 == 3'b100) || (in1 == 3'b100 && in2 == 3'b111))
	begin
		sum[3:0] =  4'b1100;	// 4 + 7 or 7 + 4
	end
end
endmodule



//=======================================================
//  Structural coding
//=======================================================

