
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================
module add3(
	//////////// INPUT //////////
	input [2:0] in1,
	input [2:0] in2,
	input       ci,

	//////////// OUTPUT //////////
	output [3:0] sum
	//output       co
);

//=======================================================
//  Temporary Variables
//=======================================================
wire temp_0;
wire temp_1;


//=======================================================
//  Structural coding
//=======================================================
fa FullAdder0(.a(in1[0]), .b(in2[0]), .ci(ci), .s(sum[0]), .co(temp_0));
fa FullAdder1(.a(in1[1]), .b(in2[1]), .ci(temp_0), .s(sum[1]), .co(temp_1));
fa FullAdder2(.a(in1[2]), .b(in2[2]), .ci(temp_1), .s(sum[2]), .co(sum[3]));

endmodule
