
//======================================================= 
//  This code is generated by Terasic System Builder 
//======================================================= 
`timescale 1ps/1ps

module add3pIII_tb;

reg [2:0] in1;
reg [2:0] in2;
reg        ci;

wire [3:0] sum;
wire 	   co;


add3 add3_DUT(.in1(in1[2:0]), .in2(in2[2:0]), .ci(ci), .sum(sum[3:0]));

 initial begin   
	ci = 1'b0;
	in1 = 3'b000;
	in2 = 3'b000;	
	#10;
 $display("in1 = %d, in2 = %d, sum = %d", in1, in2, sum);
	
	ci = 1'b0;
	in1 = 3'b000;
	in2 = 3'b001;
	#10;	
 $display("in1 = %d, in2 = %d, sum = %d", in1, in2, sum);
	
	ci = 1'b0;
	in1 = 3'b001;
	in2 = 3'b000;
	#10;
 $display("in1 = %d, in2 = %d, sum = %d", in1, in2, sum);
	
	ci = 1'b0;
	in1 = 3'b101;
	in2 = 3'b101;	
	#10;
 $display("in1 = %d, in2 = %d, sum = %d", in1, in2, sum);
	
	ci = 1'b0;
	in1 = 3'b111;
	in2 = 3'b000;
	#10;
 $display("in1 = %d, in2 = %d, sum = %d", in1, in2, sum);
	
	ci = 1'b0;
	in1 = 3'b000;
	in2 = 3'b111;
	#10;	
 $display("in1 = %d, in2 = %d, sum = %d", in1, in2, sum);

	ci = 1'b0;
	in1 = 3'b111;
	in2 = 3'b111;
	#10;	
 $display("in1 = %d, in2 = %d, sum = %d", in1, in2, sum);


	ci = 1'b0;
	in1 = 3'b110;
	in2 = 3'b010;
	#10;	
 $display("in1 = %d, in2 = %d, sum = %d", in1, in2, sum);

	ci = 1'b0;
	in1 = 3'b011;
	in2 = 3'b100;
	#10;	
 $display("in1 = %d, in2 = %d, sum = %d", in1, in2, sum);

	ci = 1'b0;
	in1 = 3'b011;
	in2 = 3'b001;
	#10;	
 $display("in1 = %d, in2 = %d, sum = %d", in1, in2, sum);

	ci = 1'b0;
	in1 = 3'b111;
	in2 = 3'b010;
	#10;	
 $display("in1 = %d, in2 = %d, sum = %d", in1, in2, sum);

	ci = 1'b0;
	in1 = 3'b011;
	in2 = 3'b011;
	#10;	
 $display("in1 = %d, in2 = %d, sum = %d", in1, in2, sum);

	ci = 1'b0;
	in1 = 3'b011;
	in2 = 3'b110;
	#10;	
 $display("in1 = %d, in2 = %d, sum = %d", in1, in2, sum);

	ci = 1'b0;
	in1 = 3'b111;
	in2 = 3'b010;
	#10;	
 $display("in1 = %d, in2 = %d, sum = %d", in1, in2, sum);

	ci = 1'b0;
	in1 = 3'b011;
	in2 = 3'b011;
	#10;	
 $display("in1 = %d, in2 = %d, sum = %d", in1, in2, sum);
  end 
endmodule 



