
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module fa(

input a,
input b,
input ci,

output wire s,
output wire co
);

//=======================================================
//  Structural coding
//=======================================================


assign s = a ^ b ^ ci;
	
assign co = a*b | a*ci | b*ci;

endmodule
