
// Bradley Manzo
// 916953788
// May 19th, 2022
// Prof Hussain Al-Asaad

//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module top(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW

	//////////// GPIO, GPIO connect to GPIO Default //////////
	// inout 		    [35:0]		GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

// Instantiates wires and local register half_max
wire temp_go, temp_end;

wire[23:0] temp_display;

wire[9:0] temp_LEDS;

reg[23:0] half_max = 24'b0111_1111_1111_1111_1111_1111;

assign LEDR[9:0] = temp_LEDS[9:0];


//=======================================================
//  Structural coding
//=======================================================

// Instantiates both Counters1 and counter2)
Counter1 c1(.reset(~KEY[0]), .enable(SW[0]), .divideby(SW[9:4]), .clk(MAX10_CLK1_50), .go(temp_go), .count(temp_end));
Counter2 c2(.reset(~KEY[0]), .enable1(SW[0]), .enable2(temp_go), .updown(SW[1]), .freerun(SW[2]), .clk(MAX10_CLK1_50), .divideby(SW[9:4]), .halfmax(half_max), .count(temp_display[23:0]), .LEDR(temp_LEDS[9:0]));

// Connects Display output to Seg7 displays
seg7 s0(.s(temp_display[3:0]), .display(HEX0));
seg7 s1(.s(temp_display[7:4]), .display(HEX1));
seg7 s2(.s(temp_display[11:8]), .display(HEX2));
seg7 s3(.s(temp_display[15:12]), .display(HEX3));
seg7 s4(.s(temp_display[19:16]), .display(HEX4));
seg7 s5(.s(temp_display[23:20]), .display(HEX5));


endmodule
