
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================
module add4bit(
	//////////// INPUT //////////
	input [3:0] a,
	input [3:0] b,
	input       ci,

	//////////// OUTPUT //////////
	output [3:0] s,
	output       co
);

//=======================================================
//  Temporary Variables
//=======================================================

// Declaring Wire Names to connect co to ci
wire temp_0;
wire temp_1;
wire temp_2;

//=======================================================
//  Structural coding
//=======================================================

// Instantiating Four Full Adders
fa FullAdder0(.a(a[0]), .b(b[0]), .ci(ci), .s(s[0]), .co(temp_0));
fa FullAdder1(.a(a[1]), .b(b[1]), .ci(temp_0), .s(s[1]), .co(temp_1));
fa FullAdder2(.a(a[2]), .b(b[2]), .ci(temp_1), .s(s[2]), .co(temp_2));
fa FullAdder3(.a(a[3]), .b(b[3]), .ci(temp_2), .s(s[3]), .co(co));

endmodule
