
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

// Full Adder Inputs
module fa(

input a,
input b,
input ci,

// Full Adder Outputs
output wire s,
output wire co
);

//=======================================================
//  Structural coding
//=======================================================

// Full Adder Equations
assign s = a ^ b ^ ci;
	
assign co = a*b | a*ci | b*ci;

endmodule
